//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataStore.EntityData
{
    using System;
    using System.Collections.Generic;
    
    public partial class TF_Collections
    {
        public TF_Collections()
        {
            this.TF_Projects = new HashSet<TF_Projects>();
            this.TF_User_Permissions = new HashSet<TF_User_Permissions>();
        }
    
        public int Collection_Id { get; set; }
        public string Name { get; set; }
        public string Host { get; set; }
        public int Type_Id { get; set; }
    
        public virtual TF_Collection_Types TF_Collection_Types { get; set; }
        public virtual ICollection<TF_Projects> TF_Projects { get; set; }
        public virtual ICollection<TF_User_Permissions> TF_User_Permissions { get; set; }
    }
}
