//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataStore.EntityData
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class testflowEntities : DbContext
    {
        public testflowEntities()
            : base("name=testflowEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TF_Case_Metrics> TF_Case_Metrics { get; set; }
        public virtual DbSet<TF_Collection_Types> TF_Collection_Types { get; set; }
        public virtual DbSet<TF_Collections> TF_Collections { get; set; }
        public virtual DbSet<TF_Projects> TF_Projects { get; set; }
        public virtual DbSet<TF_Step> TF_Step { get; set; }
        public virtual DbSet<TF_Suites> TF_Suites { get; set; }
        public virtual DbSet<TF_TestCases> TF_TestCases { get; set; }
        public virtual DbSet<TF_TestPlan> TF_TestPlan { get; set; }
        public virtual DbSet<TF_User> TF_User { get; set; }
        public virtual DbSet<TF_User_Permissions> TF_User_Permissions { get; set; }
    }
}
