//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataStore.EntityData
{
    using System;
    using System.Collections.Generic;
    
    public partial class TF_Collection_Types
    {
        public TF_Collection_Types()
        {
            this.TF_Collections = new HashSet<TF_Collections>();
        }
    
        public int Type_Id { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<TF_Collections> TF_Collections { get; set; }
    }
}
