//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataStore.EntityData
{
    using System;
    using System.Collections.Generic;
    
    public partial class TF_Step
    {
        public int Step_Id { get; set; }
        public string Name { get; set; }
        public string Results { get; set; }
        public int Parent { get; set; }
        public int TestCase_Id { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public int LastModifiedBy { get; set; }
        public System.DateTime Created { get; set; }
        public System.DateTime Modified { get; set; }
        public int External_Id { get; set; }
        public Nullable<int> Parent_External_Id { get; set; }
    
        public virtual TF_TestCases TF_TestCases { get; set; }
    }
}
