//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataStore.EntityData
{
    using System;
    using System.Collections.Generic;
    
    public partial class TF_TestPlan
    {
        public TF_TestPlan()
        {
            this.TF_Suites = new HashSet<TF_Suites>();
        }
    
        public int TestPlan_Id { get; set; }
        public string Name { get; set; }
        public int Project_Id { get; set; }
        public int External_Id { get; set; }
    
        public virtual TF_Projects TF_Projects { get; set; }
        public virtual ICollection<TF_Suites> TF_Suites { get; set; }
    }
}
