//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Security.Principal;
using System.Text;

public class FileStoreController
{
	public int UploadFile(string file, IPrincipal user)
	{
		throw new System.NotImplementedException();
	}

	public virtual void GetFilePath(int id)
	{
		throw new System.NotImplementedException();
	}

	public void UpdateFile(string file, IPrincipal user, int id)
	{
		throw new System.NotImplementedException();
	}

	public virtual void DeleteFile(int id)
	{
		throw new System.NotImplementedException();
	}

}

